spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

aladin:
  api:
    base-url: "http://www.aladin.co.kr/ttb/api/ItemList.aspx"
    query-params: "?ttbkey=%s&QueryType=BestSeller&MaxResults=%d&start=%d&SearchTarget=Book&output=js&Version=20131101"
    ttbkey: ${TTB_KEY}

place:
  api:
    bookstore:
      base-url: "http://api.kcisa.kr/openapi/API_CIA_089/request"
      key: ${PLACE_BOOKSTORE}
    cafe:
      base-url: "http://api.kcisa.kr/openapi/API_CIA_090/request"
      key: ${PLACE_CAFE}

naver:
  client-id: ${NAVER_ID}
  client-secret: ${NAVER_SECRET}